<Project>
  <PropertyGroup Condition="'$(PackageReadmeFile)' != ''">
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Condition="'$(PackageReadmeFile)' != ''">
    <PackageReference Include="Microsoft.SourceLink.GitHub"
                      Version="8.0.0"
                      PrivateAssets="All" />
  </ItemGroup>
</Project>
