<Project>
  <PropertyGroup Condition="'$(PackageReadmeFile)' != ''">
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PackageReadmeFile)' != '' And '$(MSBuildProjectName)' != 'StateForge.Core' And '$(MSBuildProjectName)' != 'StateForge.FileStore' And '$(MSBuildProjectName)' != 'StateForge.Format' And '$(MSBuildProjectName)' != 'StateForge.Security'">
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'StateForge.Core' Or '$(MSBuildProjectName)' == 'StateForge.FileStore' Or '$(MSBuildProjectName)' == 'StateForge.Format' Or '$(MSBuildProjectName)' == 'StateForge.Security'">
    <WarningsAsErrors>$(WarningsAsErrors);1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(PackageReadmeFile)' != ''">
    <PackageReference Include="Microsoft.SourceLink.GitHub"
                      Version="8.0.0"
                      PrivateAssets="All" />
  </ItemGroup>
</Project>
