<Project>
  <PropertyGroup Condition="'$(PackageReadmeFile)' != ''">
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PackageReadmeFile)' != ''">
    <WarningsAsErrors>$(WarningsAsErrors);1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(PackageReadmeFile)' != ''">
    <PackageReference Include="Microsoft.SourceLink.GitHub"
                      Version="8.0.0"
                      PrivateAssets="All" />
  </ItemGroup>
</Project>
