<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>StateForge.CloudNative</RootNamespace>
    <AssemblyName>StateForge.CloudNative</AssemblyName>
    <Nullable>disable</Nullable>
    <Version>0.26.2</Version>

    <PackageId>StateForge.CloudNative</PackageId>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
      <PackageReadmeFile>README-NUGET.md</PackageReadmeFile>
      <PackageTags>stateforge;session-state;aspnet;aspnetcore;distributed-cache;filestore;stfg2</PackageTags>
      <PackageProjectUrl>https://github.com/stateforge/stateforge</PackageProjectUrl>
      <RepositoryUrl>https://github.com/stateforge/stateforge</RepositoryUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\StateForge.Core\StateForge.Core.csproj" />
    <ProjectReference Include="..\StateForge.FileStore\StateForge.FileStore.csproj" />
    <ProjectReference Include="..\StateForge.AspNetCore\StateForge.AspNetCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README-NUGET.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
