<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>StateForge.CloudNative</RootNamespace>
    <AssemblyName>StateForge.CloudNative</AssemblyName>
    <Nullable>disable</Nullable>
    <Version>0.15.0</Version>

    <PackageId>StateForge.CloudNative</PackageId>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\StateForge.Core\StateForge.Core.csproj" />
    <ProjectReference Include="..\StateForge.FileStore\StateForge.FileStore.csproj" />
    <ProjectReference Include="..\StateForge.AspNetCore\StateForge.AspNetCore.csproj" />
  </ItemGroup>
</Project>
