<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>StateForge.Remote.Tests</RootNamespace>
    <AssemblyName>StateForge.Remote.Tests</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.64.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.5.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.5.2" />
    <ProjectReference Include="..\..\src\StateForge.Remote\StateForge.Remote.csproj" />
    <ProjectReference Include="..\..\src\StateForge.Remote.Host\StateForge.Remote.Host.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
