<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>StateForge.ShardingTests</RootNamespace>
    <AssemblyName>StateForge.ShardingTests</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <Version>0.28.3</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StateForge.Core\StateForge.Core.csproj" />
    <ProjectReference Include="..\StateForge.FileStore\StateForge.FileStore.csproj" />
    <ProjectReference Include="..\StateForge.Performance\StateForge.Performance.csproj" />
  </ItemGroup>
</Project>
