<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.2.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.2.2" />
    <ProjectReference Include="..\..\src\StateForge.FileStore\StateForge.FileStore.csproj" />
  </ItemGroup>
</Project>
