<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>StateForge.PrometheusTests</RootNamespace>
    <AssemblyName>StateForge.PrometheusTests</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <Version>1.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StateForge.Prometheus\StateForge.Prometheus.csproj" />
  </ItemGroup>
</Project>
