<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>StateForge.FormatTests</RootNamespace>
    <AssemblyName>StateForge.FormatTests</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <Version>0.19.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StateForge.Format\StateForge.Format.csproj" />
  </ItemGroup>
</Project>
