<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StateForge.CloudNative\StateForge.CloudNative.csproj" />
    <ProjectReference Include="..\..\src\StateForge.Telemetry.AspNetCore\StateForge.Telemetry.AspNetCore.csproj" />
  </ItemGroup>
</Project>
